services:
  techup-nginx:
    container_name: "techup-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - techup-app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    networks:
    - default

  techup-app:
    container_name: "techup-app"
    build:
      context: ./docker/php
    depends_on:
      - techup-mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules 
      - ./vendor:/var/www/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/nginx/logs:/var/log/nginx
    working_dir: /var/www
    networks:
    - default

  techup-mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "techup-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_DATABASE=techup_db
    - MYSQL_USER=laraveluser
    - MYSQL_PASSWORD=laravelpass123
    ports:
      - 3306:3306
    networks:
    - default

  techup-redis:
    image: redis:alpine
    container_name: "techup-redis"
    ports:
      - 16379:6379
    networks:
    - default

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - techup-mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=techup-mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    ports:
      - "3001:80"
    networks:
    - default

networks:
  default:
    name: techup-net
